name: Deploy Swagger UI to Pages

on: workflow_dispatch

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: clone swagger-ui
              run: git clone https://github.com/swagger-api/swagger-ui.git
            - name: checkfiles
              run: ls -la
            - name: copy
              run: cp -r swagger-ui/dist/* docs/
            - name: copy 2
              run: cp openapi.yml docs/
            - name: checkfiles 2
              run: ls -la
            - name: checkfiles 3
              run: ls docs -la
