name: Deploy Swagger UI to Pages

on: workflow_dispatch

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Inspect files after checkout
              run: ls -la
            - name: show current directory after checkout
              run: pwd
            - name: show all branches after checkout
              run: git branch -a
