name: Deploy Swagger UI to Pages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: clone swagger-ui
        run: git clone https://github.com/swagger-api/swagger-ui.git
      - name: checkfiles
        run: ls -la
      - name: copy
        run: cp -r swagger-ui/dist/* docs/
      - name: copy 2
        run: cp openapi.yml docs/
      - name: checkfiles 2
        run: ls -la
      - name: checkfiles 3
        run: ls docs -la
      - name: check js
        run: cat docs/swagger-initializer.js
      - name: replace url
        run: sed -i 's|https://petstore.swagger.io/v2/swagger.json|./docs/openapi.yml|g' ./docs/swagger-initializer.js
      - name: check js 2
        run: cat docs/swagger-initializer.js
      - name: Remove symlinks and hardlinks
        run: find docs/ -type l -exec rm -f {} \;
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/
  deploy:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
